---
title: "LR travel"
author: "Lintong Li"
date: "2022-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
LRQ1_22 <- read_csv("~/Desktop/2022-Q1_LRTravelTimes.csv",show_col_types = FALSE)
LRQ2_22 <- read_csv("~/Desktop/2022-Q2_LRTravelTimes.csv",show_col_types = FALSE)
LRQ3_22 <- read_csv("~/Desktop/2022-Q3_LRTravelTimes.csv",show_col_types = FALSE)
LRQ4_21 <- read_csv("~/Desktop/LRTravelTimesQ4_21.csv",show_col_types = FALSE)
```


```{r}
LROct <- LRQ4_21 %>% filter(service_date == "2021-10-25"| service_date == "2021-10-26"|service_date == "2021-10-27"| service_date == "2021-10-28"| service_date == "2021-10-29"| service_date == "2021-10-30"| service_date == "2021-10-31")
LRNov <- LRQ4_21 %>% filter(service_date == "2021-11-22"| service_date == "2021-11-23"|service_date == "2021-11-24"| service_date == "2021-11-25"| service_date == "2021-11-26"| service_date == "2021-11-27"| service_date == "2021-11-28")
LRDec <- LRQ4_21 %>% filter(service_date == "2021-12-20"| service_date == "2021-12-21"|service_date == "2021-12-22"| service_date == "2021-12-23"| service_date == "2021-12-24"| service_date == "2021-12-25"| service_date == "2021-12-26")
LRJan <- LRQ1_22 %>% filter(service_date == "2022-01-24"| service_date == "2022-01-25"|service_date == "2022-01-26"|service_date == "2022-01-27"| service_date == "2022-01-28"| service_date == "2022-01-29"| service_date == "2022-01-30")
LRFeb <- LRQ1_22 %>% filter(service_date == "2022-02-21"|service_date == "2022-02-22"| service_date == "2022-02-23"| service_date == "2022-02-24"| service_date == "2022-02-25"| service_date == "2022-02-26"|service_date == "2022-02-27")
LRMar <- LRQ1_22 %>% filter(service_date == "2022-03-21"|service_date == "2022-03-22"| service_date == "2022-03-23"| service_date == "2022-03-24"| service_date == "2022-03-25"| service_date == "2022-03-26"|service_date == "2022-03-27")
LRApr <- LRQ2_22 %>% filter(service_date == "2022-04-18"|service_date == "2022-04-19"| service_date == "2022-04-20"| service_date == "2022-04-21"| service_date == "2022-04-22"| service_date == "2022-04-23"|service_date == "2022-04-24")
LRMay <- LRQ2_22 %>% filter(service_date == "2022-05-23"|service_date == "2022-05-24"| service_date == "2022-05-25"| service_date == "2022-05-26"| service_date == "2022-05-27"| service_date == "2022-05-28"|service_date == "2022-05-29")
LRJun <- LRQ2_22 %>% filter(service_date == "2022-06-20"|service_date == "2022-06-21"| service_date == "2022-06-22"| service_date == "2022-06-23"| service_date == "2022-06-24"| service_date == "2022-06-25"|service_date == "2022-06-26")
LRJul <- LRQ3_22 %>% filter(service_date == "2022-07-25"|service_date == "2022-07-26"| service_date == "2022-07-27"| service_date == "2022-07-28"| service_date == "2022-07-29"| service_date == "2022-07-30"|service_date == "2022-07-31")
LRAug <- LRQ3_22 %>% filter(service_date == "2022-08-22"|service_date == "2022-08-23"| service_date == "2022-08-24"| service_date == "2022-08-25"| service_date == "2022-08-26"| service_date == "2022-08-27"|service_date == "2022-08-28")
LRSep <- LRQ3_22 %>% filter(service_date == "2022-09-19"|service_date == "2022-09-20"| service_date == "2022-09-21"| service_date == "2022-09-22"| service_date == "2022-09-23"| service_date == "2022-09-24"|service_date == "2022-09-25")
LRJan$month <- "Jan"
LRFeb$month <- "Feb"
LRMar$month <- "Mar"
LRApr$month <- "Apr"
LRMay$month <- "May"
LRJun$month <- "Jun"
LRJul$month <- "Jul"
LRAug$month <- "Aug"
LRSep$month <- "Sep"
LROct$month <- "Oct"
LRNov$month <- "Nov"
LRDec$month <- "Dec"
LR <- rbind(LRJan,LRFeb,LRMar,LRApr,LRMay,LRJun,LRJul,LRAug,LRSep,LROct,LRNov,LRDec)
LR$day_name <- weekdays(LR$service_date)
LR$season <- case_when(
  between(LR$service_date, as.Date("2021-11-30"), as.Date("2022-03-01")) ~ "Winter",
  between(LR$service_date, as.Date("2022-02-28"), as.Date("2022-06-01")) ~ "Spring",
  between(LR$service_date, as.Date("2022-05-31"), as.Date("2022-09-01")) ~ "Summer",
  TRUE ~ "Fall"
)
stops <- read.csv("~/Desktop/stops.txt",header = TRUE)
stop3 <- left_join(LR, stops, by = c("from_stop_id"="stop_code"))
stop4 <- left_join(stop3, stops, by = c("to_stop_id"="stop_code"))
LR_clean <- select(stop4,c("service_date","route_id" ,"travel_time_sec","month","day_name","season","stop_id.x", "stop_name.x","stop_desc.x","stop_lat.x","stop_lon.x","stop_id.y","stop_name.y","stop_desc.y", "stop_lat.y","stop_lon.y"))
```



```{r}
LRshiny <- LR_clean %>%
  group_by(day_name,season,route_id,stop_name.x,stop_name.y,stop_lat.x,stop_lon.x,stop_lat.y,stop_lon.y) %>%
 summarise_at(vars(travel_time_sec), list(avg_time = mean))
```

```{r}
write.csv(LRshiny,"~/Desktop/LRshiny.csv")
```

